microsoft/OpenAPI.NET.OData

src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
=> set $select, $orderby and #expand as comma-separated values

src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Common/EdmModelHelper.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiPathsGeneratorTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Microsoft.OpenAPI.OData.Reader.Tests.csproj, test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Contract.OData.xml
Implementation of adding methods from parent classes to children for all entity sets and singletons.
See description in #46
=> Adding methods from parent classes in to children classes

src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
"simple" is not supported in query parameters for OpenAPI v3. https://swagger.io/docs/specification/describing-parameters/
=> Change all query parameters from "simple" to "form"

src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs, src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiLinkGenerator.cs, src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs, src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetGetOperationHandler.cs, src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs, src/Microsoft.OpenApi.OData.Reader/Operation/SingletonGetOperationHandler.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Closes https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/185
This PR adds OpenAPI Link properties to EntitySet type Get response objects.
=> Adds Links to EntitySet type Get response objects

src/OoasGui/MainForm.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/101
Proposes:
- Taking advantage of asynchronous programming to help make the GUI feel more responsive during the conversion of CSDL to OpenAPI
=> Makes the GUI tool more responsive

src/Microsoft.OpenApi.OData.Reader/Edm/EdmTypeExtensions.cs, src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj, test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
=> Ensure no single quotes are added to URL path parameters of temporal type 

src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
=> Bump version to 1.2.0

.github/workflows/ci-cd.yml, .github/workflows/sonarcloud.yml
more information https://docs.opensource.microsoft.com/github/apps/permission-changes/
=>  - adds permissions to workflows

src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
=> Reverts collection literal implementation breaking build

.github/CODEOWNERS
- replaces baywet by coseguera since he is new the crew leader
=> - removes peter

.azure-pipelines/ci-build.yml, .github/workflows/ci-cd.yml, .github/workflows/codeql-analysis.yml, .github/workflows/sonarcloud.yml, .vscode/launch.json, src/OoasGui/OoasGui.csproj, src/OoasUtil/OoasUtil.csproj, test/Microsoft.OpenAPI.OData.Reader.Tests/Microsoft.OpenAPI.OData.Reader.Tests.csproj, tool/UpdateDocs/UpdateDocs.csproj
=> Upgrade to .NET 8

.azure-pipelines/ci-build.yml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/540
=> Update build pipeline to use governed 1ES compliant template

src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs, src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj, test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/541
Partially fixes https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2787
=> Adds support for `IndexableByKey` restrictions annotations on entity sets

src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
=> fix: wrong dependency for tasks analysis

src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj, src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json, test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/585
=> Updates tag names for actions/functions operations

src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
pending on:
- #627
- #628
- #629
- #630
=> chore: bumps version for release

scripts/ValidateProjectVersionUpdated.ps1
=> ci: fixes version check script

.github/policies/resourceManagement.yml
similar to https://github.com/microsoft/OpenAPI.NET/pull/2180
=> ci: adds issues automation configuration

.github/CODEOWNERS
=> security: normalizes code owners to teams

.github/CODEOWNERS
=> security: aligns code owners with main branch
