microsoft/OpenAPI.NET.OData

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiExampleGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Microsoft.OpenAPI.OData.Reader.Tests.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
Currently using Azure API management you receive a ton of errors on the examples section (e.g. [#/components/schemas/type/example/property] Data and type mismatch found.) leading to not being able to import the file.
Added more types as examples to fix this.
Updated Microsoft.OpenApi to the latest version to solve DateTimeOffset serialization. There is an issue with the version currently used where DateTimeOffset is serialized as 0001-01-01T00:00:00.0000000+00:00 instead of "0001-01-01T00:00:00.0000000+00:00".
> Add more types to examples

- src/Microsoft.OpenApi.OData.Reader/Common/CryptographyExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationImportOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionImportOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Currently the OpenAPI.NET.OData implementation is not FIPS compliant, as it uses the non-compliant MD5 has. For any environment that has FIPS compliance enabled, the converter will fail with a FIPS error, as MD5 hash provider's behavior is to throw in that case. 
Changing to SHA256 hash for FIPS compliance.
> Change encryption for fips compliance

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.Release.nuspec
Closes https://github.com/microsoft/OpenAPI.NET.OData/issues/49
Proposes:
- Fixing the missing `NavigationProperty `descriptions in the converted Microsoft Graph OpenApi descriptions from CSDL.
> Fixes missing NavigationProperty descriptions in OpenApi

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
Related to: https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/196
Proposes:
- Adding support to OpenApi for PowerShell/AutoREST consumption.
- This adds an `x-ms-discriminator-value` extension to the derived types of a response schema, and
- a `Discriminator` object to response schemas.  
- Creating a config. setting to toggle this feature on/off.
> Adds discriminator support to OpenApi

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPath.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiPathsGeneratorTests.cs
Fixes #60 
Added simple PathPrefix to ConvertSettings to match ODataRoute prefix without affecting 'servers' declaration in OAS file.
Add test to match.
This aids with mocking tools that only understand absolute paths and cannot parse server entries to split DNS segments from path segments.
> Added simple PathPrefix to ConvertSettings to match ODataRoute prefix without affecting 'servers' declaration in OAS file.

- src/Microsoft.OpenApi.OData.Reader/Operation/RefPatchOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefPostOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes #77
This PR fixes the casing of the type in code and test resources.
> Fix casing of OpenAPI type "String" for RefPatchOperationHandler and RefPostOperationHandler

- src/Microsoft.OpenApi.OData.Reader/Edm/EdmModelExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/EdmOperationProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/EdmSpatialTypeVisitor.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiExampleGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OData/ODataConstants.cs
- src/OoasUtil/ComLineProcesser.cs
- src/OoasUtil/FileOpenApiGenerator.cs
- src/OoasUtil/OpenApiGenerator.cs
- src/OoasUtil/Program.cs
- src/OoasUtil/README.md
- src/OoasUtil/UrlOpenApiGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Common/EdmModelHelper.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/EdmModelExtensionsTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
Add model reference support to library and command line utility.   
Added basic model reference support to the library.
Added similar support to the commandline utility for local files only.
Also added a lot more conversion options flags to the command line.
Added library tests to match.
> Add model reference support to library and command line utility.   

- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/97
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/510
- Appends the `EntityType` name of an`ODataKeySegment` in entity action/function paths. This should help in preventing possible duplicate `operationIds` in entity vs entityset action/function paths.
- Tests have been updated to validate this fix.
> Fixes potential duplicate operationIds in action/function paths

- src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionImportOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/91
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/511
- The current _Example_ property defined under parameters is currently only used to define the _DocumentationURL_ property value. This can be appended to the _Description_ property. This will help in preventing the potential occurrences of both _example_ and _examples_ properties, which are mutually exclusive. 
- Tests have been added to validate this fix.
> Fix: Removes example property in path parameter objects

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiExampleGenerator.cs
We have an OData model with TypeDefinition.
```
<TypeDefinition Name="MyID" UnderlyingType="Edm.Int64" />
```
Currently this crashes with `OpenApiException` ("Not supported") in `OpenApiExampleGenerator.GetTypeNameForExample`.
I made a change handling `EdmTypeKind.TypeDefinition` by extracting the underlying (primitive) type. I'm not 100% sure if this is the correct way of handling it, but at least it now doesn't crash and generates valid OpenAPI schema.
Please let me know if I should write tests or make some other changes.
> Add support for EdmTypeKind.TypeDefinition

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/107
Fixes microsoftgraph/microsoft-graph-devx-api#618
This PR:
- Explicitly sets the `Explode` properties to `false` for `$orderby`, `$select` and `$expand` OData query parameters, for `style: form`.
- Adds tests to validate the creation of the above query parameters, and in extension, validate that `explode: false` is always set.
> Set parameters' explode property to false

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityOperationalHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityPutOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityPutOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/109
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/637
This PR:
- Updates the `ODataPathProvider.cs` to ensure  generation of paths for stream properties declared both in the target type definitions and their base types. 
- Updates the `ODataPathProviderTests.cs` to validate the above. Also refactors the target test for readability and conciseness.
- Refactors the `MediaEntityOperationalHandler.cs` class and its derived classes to use the abstraction - 
`ODataNavigationSourceSegment` to define the `NavigationSourceSegment` for a path. This helps in general maintainability and code conciseness.
> [Fix] Generate paths for stream properties in base types of entities

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/114
This PR: 
- Updates the `ODatPathProvider.cs` class to allow skipping of generation of action/function paths for non-contained navigation properties.
- Updates the test class with test methods to validate the above.
> Skips generation of action/function paths for non-contained nav. props.

- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Closes https://github.com/microsoft/OpenAPI.NET.OData/issues/116
This PR:
- Updates the `EdmOperationOperationHandler.cs` class by updating the response schema of actions/functions that return a collection.
> Resolves response schemas of actions/functions that return collection

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Graph.Beta.OData.xml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/122
This PR:
- Adds a `Content` property and a media type object to the structured & collection-valued parameters property of functions to indicate that the parameter values are serialized as JSON.
- Adds test for the above.
> Fixes structured & collection-valued parameters of functions

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationImportOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/126
This PR:
- Fixes the schema of response objects of operations that return a single primitive type
- Refactors common code that creates `OpenApiResponses` for `IEdmOperation`s and `IEdmOperationImport`s into a common function that can be reused by both.
> Fixes response objects for operations that return single primitive type values

- src/Microsoft.OpenApi.OData.Reader/PathItem/DollarCountPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntitySetPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/MediaEntityPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/MetadataPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationImportPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/PathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/RefPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/SingletonPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntitySetPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/MediaEntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/OperationImportPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/OperationPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/RefPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/SingletonPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
fixes #154 a bug where path items would be missing descriptions
> Note: #149 will need to be updated to add a path item description as well once merged
> adds descriptions for path items

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefGetOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ODataTypeCastGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> makes collection responses reusable

- docs/csdl/TripService.xml
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityPatchOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandlerProvider.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ComplexPropertyItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntityPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/UpdateRestrictionsType.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/ComplexPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntitySetPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/106
Fixes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/607
This PR adds  support for PUT operations for **entity sets** , **navigation properties** and **complex types** based on the annotated Http method in the _UpdateMethod_ property of _Org.OData.Capabilities.V1.UpdateRestrictions_ annotation for a given target element.
See: https://github.com/oasis-tcs/odata-vocabularies/blob/053724df1ab5d19cc198f2a52cf8a85a2be08d79/vocabularies/Org.OData.Capabilities.V1.xml#L676-L677
> Add support for PUT operation on entity sets and navigation properties based on UpdateMethod annotation

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiErrorSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
- fixes #172 
- moved error definitions under main namespace
- renames types to avoid conflicts with native types or naming conventions
> errors naming conventions improvements

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiErrorSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSecurityRequirementGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSpatialTypeSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/SingletonGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/SingletonPatchOperationHandler.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/171
This PR proposes:
- Setting `UnresolvedReference = true` for schemas with `OpenAPIReference` objects which are references to other model objects.
> [Fix] Set `UnresolvedReference=true` for schemas with OpenAPIReference objects

- src/Microsoft.OpenApi.OData.Reader/Edm/EdmModelExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/123
This PR proposes:
- Updating the expansion logic for containment navigation properties to evaluate based on whether the navigation property  has been visited before and not the navigation property type.
NB: This approach expands on all containment navigation properties. This ends up exploding the number of paths significantly.
> Updates navigation property expansion logic

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ComplexPropertyItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiPathItemGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiPathsGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/ComplexPropertyPathItemHandlerTests.cs
This PR:
- Renames the setting property `UseRestrictionAnnotationsToGeneratePathsForComplexProperties` to `UseRestrictionAnnotationsToGenerateComplexPropertyPaths`. The new name is more terse.
> Renames setting property

- .github/ISSUE_TEMPLATE/workflows/azure-pipelines_nightly.yml
> - attempt to fix nightly build

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmFunctionImportOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/SingletonGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/PathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/159
This PR add support for declaring path parameters on the [path item](https://spec.openapis.org/oas/latest.html#path-item-object) object instead of the [operation ](https://spec.openapis.org/oas/latest.html#operation-object) object. This feature is controlled by a new flag (`DeclarePathParametersOnPathItem`) on `OpenApiConvertSettings`
Example usage:
---
```cs
OpenApiConvertSettings settings = new()
{
DeclarePathParametersOnPathItem = true,
};
ODataContext context = new ODataContext(model, settings);
```
Example output
---
```diff
'/Airports/{IcaoCode}':
description: Provides operations to manage the collection of Airport entities.
get:
tags:
- Airports.Airport
summary: Get entity from Airports by key
operationId: …
```
> Add support for declaring path parameters on path item object instead of operation object

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
Bumps the preview version to `1.0.10-preview3` and updates the release note.
> Bumps preview version and update release note

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiLinkGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/SingletonGetOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiLinkGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/74
This PR:
- Adds support for `OpenApiLink`s for actions and functions.
- Adds tests for `OpenApiLinkGenerator.cs` class.
- Updates integration tests.
> Creates links for actions and functions

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/200
This PR:
- Sets the response types of functions returning `Edm.Stream` from `application/json` to `application/octet-stream`.
- Updates unit test and integration file to validate the above.
> Sets the response type of functions returning `Edm.Stream` to `application/octet-stream`

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiLinkGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/199
This PR:
- Fixes how OData type cast paths from navigation properties are being generated. The entity type targeting the navigation property is used in the argument in the method `CreateTypeCastPaths()` instead of the entity type declaring the navigation property.
- Updated tests and integration test file due to the above fix.
- Added a new setting `ExpandDerivedTypesNavigationProperties` that can be used to evaluate whether or not to expand derived types navigation properties. When this setting is set to `true`, we end up generating over 219K paths for the beta version of Graph (with a maximum of 1 type cast segment allowed in a path). This is because we have deeply nested derived types in our metadata. This needs to be set …
> Fixes generation of `ODataTypeCast` paths

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ComplexPropertyItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntityPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntitySetPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ODataTypeCastPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationImportPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/PathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/SingletonPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/ComplexPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntitySetPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/ODataTypeCastPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/OperationImportPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/OperationPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/SingletonPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/192
This PR:
- Provides a means of reading custom attribute values from the CSDL through the setting `CustomXMLAttributesMapping`, which a client can use to provide a dictionary mapping of custom attribute names and extension names. The values of these custom attribute names will be extracted from the Edm model from an element if it contains the custom attribute. The values will then be mapped to the custom extension values provided in the dictionary and added to the relevant extensions object in the OpenAPI document.
- Tests have been added (and integration files updated) to validate the above.
> Adds support for reading custom attributes

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/219
Retrieve list of derived types for structured types and adds it to the mapping property of the discriminator object.
> Include correct list of discriminator information

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/201
This PR:
- Removes the conditional expressions that prevent generation of bound operations for a given set of paths when the conditional expression that comes before this is `true`. This also necessitated refactoring of the target `private` method signatures and local variables.
- Updates the integration test results as a product of the above fix.
- With the above fix, the path `/users/{user-id}/followedSites/microsoft.graph.add` can now be generated:
> Fixes missing bound operations on some navigation property paths

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/EdmModelOpenApiExtensionsTest.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/221
This PR:
- Adds a new convert setting `AppendBoundOperationsOnDerivedTypes` that allows configuring whether or not to append bound operations on derived types. This is enabled by default - `true`.
- Updates the relevant tests to validate use of the above setting flag when generating paths for bound operations on derived types.
> Enables configuring appending bound operations on derived types

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiErrorSchemaGeneraratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
Fixes (#218)
Add error ranges for OData actions if ErrorResponsesAsDefault is set to false.
> Fix error ranges for OData actions

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/233
This PR: 
- Fixes the function that fetches the derived types of structured types and adds them to the discriminator object. The fix includes retrieving the derived types of complex properties and removing the condition that checks for base types before adding the discriminator object. Discriminator objects are not only required to be added to structured types which have base types. 
- Adds test to validate the above fix.
- Adds release note info.
> Adds discriminator object to complex types which have derived types

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/243
This PR does the following:
Given an example of this schema, which is a base type, which exposes the discriminator mappings as shown:
The following is accomplished:
1. Adds the @odata.type property in the properties' object
2. Marks the @odata.type property as required
3. In the @odata.type property, sets the default value to '#microsoft.graph.entity
4. Updates tests to validate the above.
After the above, the schema should appear as below:
> Adds `@odata.type` property and makes this a required property in schemas that have discriminator objects

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiEdmTypeSchemaGeneratorTest.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> Represent nullable references within anyOf correctly

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/248
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/240
This PR:
- Finds all derived types for a given type and adds this to the discriminator mapping.
- Appends the `@odata.type` property to the derived types, and marks this as a required property.
- Updates tests to validate the above.
- Bumps library package to `v1.0.11` and add release notes.
The generated OpenAPI document with the above changes looks like below for:
**microsoft.graph.fileAttachment**
**microsoft.graph.mobileApp**
```
microsoft.graph.mobileApp:
allOf:
- $ref: '#/components/schemas/microsoft.graph.entity'
- title: mobileApp
required:
- '@odata.type'
type: object
properties:
..........
'@odata.type':
type: string
default: …
```
> List all derived types in discriminator mapping and append `@odata.type` property to all derived types

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmActionOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmFunctionOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
Fixes #231 
Add pageable extension to responses of actions and functions that return a collection
> Fix response schemas of actions and functions that return a collection to contain the nextLink property.

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/249
This PR:
- Retrieves `RestrictedProperties` annotations annotated directly on navigations properties. 
If the entity type targeted by this navigation property also has `RestrictedProperties` annotations, this will take precedence first.
- Retrieves `IndexableByKey` annotation annotated directly on a navigation property. 
- Updates tests appropriately.
> Retrieves `RestrictedProperties` annotations annotated directly on navigations properties

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/251
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/252
This PR: 
- Appends OData query parameters to functions: `$top`, `$skip`, `$filter`, `$search`, `$count`, `$select`, `$top`
- Update tests and integration files.
- Refactors the retrieval of `IndexableByKey` annotation.
> Appends OData query parameters to functions

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OData/ODataConstants.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/196
This PR:
- Adds an `@odata.count` as a pagination property for collection responses. Together with `@odata.nextLink` these are componentized and reused.
- Adds a new setting `Settings.EnableCount` which controls whether to set the `@odata.count`.
- When `Settings.EnablePagination` and `Settings.EnableCount` are enabled, these properties alongside the base properties of a type are appended to an `allOf` schema.
- Updates test.
When `Settings.EnablePagination = true` and `Settings.EnableCount = true` the new schema for collections would look like:
And the `BaseCollectionPaginationCountResponse` schema:
And the `BaseCollectionCountResponse` schema:
> Adds `@odata.count` parameter to collection responses

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/274
This PR:
- Sets `explode = false` and `style = form` for the OData query options: `$top`, `$skip`, `$search`, `$filter`, `$count`
- Update tests to validate the above.
- Update integration test files.
> Set `explode = false` and `style = form` for OData query options

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataOperationSegment.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataOperationSegmentTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/259
This PR:
- Aliases optional parameters of OData functions by appending `@` together with the parameter name to denote the parameter alias.
- Updates tests to validate the above
Paths of functions with optional parameters will look like below:
> Alias optional parameters of OData functions

- src/Microsoft.OpenApi.OData.Reader/Edm/EdmModelExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiRequestBodyGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmActionOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationImportOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> Eliminate duplicated request bodies and responses for actions/functions

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityOperationalHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/CapabilitiesConstants.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Core/CoreConstants.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntitySetPostOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityPutOperationHandlerTests.cs
Fixes #254 
This PR
- Uses `Computed` annotation in the CSDL to declare property as `ReadOnly`
> Use Computed annotation in the CSDL to declare property as ReadOnly

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ComplexPropertyItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntityPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntitySetPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/ODataTypeCastPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationImportPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/OperationPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/SingletonPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> Add `x-ms-navigationProperty` extension to navigation properties

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- src/OoasGui/MainForm.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/282
- Adds a new convert setting `RefBaseCollectionPaginationCountResponse` which can be used to toggle between referencing the `BaseCollectionPaginationCountResponse` which contains the schemas for `@odata.count` and/or `@odata.nextLink`. By default this defaults to `true`
- [Minor] Refactors the conversion and save processes in the `MainForm` to facilitate faster debugging and testing with the GUI tool.
> Use convert setting to toggle between referencing `@odata.count` and `@odata.nextLink`

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
Fixes #120
This PR:
- Adds alternate key parameters for single and multiple property keys
> Add support for alternate key parameters

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/265
Proposes:
- Adding support for update and delete operations on non-containment navigation properties when restrictions annotations are explicitly set to true.
- Updates tests to validate the above.
- Updates integration files.
> Adds create and update operations on non-containment nav. props when restrictions annotations are explicitly set to true

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/EdmOperationExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/EdmTypeExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OData/ODataConstants.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmActionOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmFunctionOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
Fixes #285 
This PR 
- Renames setting from `RefBaseCollectionPaginationCountResponse` to `EnableODataAnnotationReferencesForResponses` to make it apply for all the [control information](http://docs.oasis-open.org/odata/odata-json-format/v4.0/cs01/odata-json-format-v4.0-cs01.html#_Toc365464684) in the response i.e. `@odata.nextLink`, `@odata.deltaLink` and `@odata.count` in our case
- Adds `@odata.nextLink` for all actions and functions that return a collection if `EnablePagination = true`
- Creates referenceable schema named `BaseDeltaFunctionResponse` if there's at least one delta function in the model and `EnableODataAnnotationReferencesForResponses = true`
- References `BaseDeltaFunctionResponse` schema for delta functions if `EnableODataAnnotationReferencesForResponses = true`
- Adds …
> Generate `odata.nextLink` and `odata.deltaLink` properties on delta functions response schemas

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiPathItemGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiPathItemGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/148
This PR:
- Ensures `PathItems` with no operations are not added to the list of paths.
- Adds a test to validate this.
> Omit paths with `PathItems` without any operation

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/DollarCountGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ODataTypeCastGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/RefGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/207
This PR:
- Adds custom parameters to `$count` and `ODataTypeCast` paths' `Get` operations where either the target navigation property or navigation source has been appropriately annotated with the `CustomHeaders` property in its `ReadRestrictions` annotation.
- Adds a new test class and test methods for `DollarCountGetOperationHandler.cs` --> `DollarCountGetOperationHandlerTests.cs`
- Updates some tests
- Updates some integration test files
NB: In response to this [comment](https://github.com/microsoft/OpenAPI.NET.OData/issues/207#issuecomment-1131601713), we already do add custom headers to navigation properties, and index endpoints where appropriate.
> Add custom parameters to `$count` and `ODataTypeCast` paths' `Get` operations

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/304
This PR:
- Adds support for setting the `default` value of the `@odata.type` property in the schema of derived types.
- Adds a new convert setting for setting this `default` value. The default value is `true`, meaning the default value will always be emitted. If `false` the value will be set conditionally based on whether the derived type's base type is abstract (and not entity) and is referenced in the properties of a structural property or an action.
- Updates existing tests and adds a new test to validate the above.
> Adds support for configuring the `default` value of derived types' `@odata.type` property

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataKeySegment.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPath.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiPathsGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Common/EdmModelHelper.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityDeleteOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes #120 
This PR:
- Adds new paths for entities that have alternate keys
- Renames the summary and OperationId of operations to include key name
- Add a setting to enable the generation of paths with alternate keys
> Add support for paths with alternate keys

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
This PR: 
- Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/84
- Finds all the derived types for a schema element and not just the directly derived types for this element.
- Updates test to validate the above.
> Finds all the derived types for a schema element

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityDeleteOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes #329 
This PR
- Removes 'ById' suffix from OperationIds for EntitySet operations and only adds the prefix for operations that use alternate keys
- Updates tests
> Only add 'By{Key}' suffix to OperationIds for alternate key paths

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> Update key path parameter descriptions

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/EdmOperationProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiLinkGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/347
> [Fix] Skips adding a `$count` path if a similar `count()` function path exists

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiPathItemGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/343
> Checks whether path exists before adding it to the paths dictionary

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataOperationSegment.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataTypeCastSegment.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- src/OoasGui/MainForm.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataOperationSegmentTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataTypeCastSegmentTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ODataTypeCastGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/ODataTypeCastPathItemHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/348
This PR:
- Removes the base namespace identifier from operation segments.
- To remove the namespace to make unqualified calls, set the convert setting `EnableUnqualifiedCall=true` and set the `BaseNamespace` value to the base namespace value that needs to be stripped.
> Strips namespace prefix from operation segments and aliases type cast segments

- src/Microsoft.OpenApi.OData.Reader/Common/Constants.cs
- src/Microsoft.OpenApi.OData.Reader/Common/OpenApiOperationExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiResponseGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityOperationalHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityPutOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityPutOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/310
This PR:
- Returns response status code 2XX for `PUT` operations of stream properties  when `UseSuccessStatusCodeRange` = `true`
- Adds schema reference to the content property of the response object of _content_ stream properties when `UseSuccessStatusCodeRange` = `true`.
Response object of the endpoint: `/drives/{drive-id}/items/{driveItem-id}/content` will be:
when `UseSuccessStatusCodeRange` = `true`
> [Fix] Returns response status code 2XX for `PUT` operations of stream properties  when `UseSuccessStatusCodeRange` is enabled

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/314
This PR:
- Append a `$value` segment if base type of entity type has stream and does not contain a structural property named `content`
- Updates tests.
> Adds `$value` segment to paths with entity types with base types with `HasStream=true`

- src/Microsoft.OpenApi.OData.Reader/Common/CryptographyExtensions.cs
> Make hasher static and readonly in CryptographicExtensions

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefDeleteOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyDeleteOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/366
This PR:
- Ensures that `delete` methods always return status code `204`. This is regardless of whether `UseSuccessStatusCodeRange` is `true`.
- Adds test to validate the above.
> [Fix] `DELETE` methods should always return response status code `204`

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataContext.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Core/RevisionRecord.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Core/RevisionType.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Vocabulary/Capabilities/RevisionRecordTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/372
> [Fix] Adds support for all `Org.OData.Core.V1.RevisionKind` enum values

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/364
This PR:
- Gets the directly annotated `CountRestriction` annotation for navigation properties. Uses this annotation (if exists) to determine whether or not to create $count segments for navigation properties.
- Update integration tests.
- Update release notes.
Related to:
- https://github.com/microsoftgraph/msgraph-metadata/issues/328
- https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2472
> Use directly annotated `CountRestriction` annotations when creating `$count` segments for col-valued navigation properties

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/371
This PR:
- Fetches navigation properties from base types of the entity type targeting a given navigation property.
- Updates tests.
> [Fix] Retrieves navigation properties from base types

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/CapabilitiesConstants.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/323, https://github.com/microsoft/OpenAPI.NET.OData/issues/232
**This PR:**
- Uses the annotations `Org.OData.Core.V1.RequiresExplicitBinding` in operations and `Org.OData.Core.V1.ExplicitOperationBindings` in model elements to associate which operations are to be generated for which elements.
- Updates the unit and integration tests.
- Updates the release notes.
**How it works**
Take for example the operation:
```XML
<Action Name="getMemberObjects" IsBound="true">
<Annotation Term="Org.OData.Core.V1.RequiresExplicitBinding"/>
<Parameter Name="bindingParameter" Type="graph.directoryObject" Nullable="false" />
<Parameter Name="securityEnabledOnly" Type="Edm.Boolean" />
<ReturnType Type="Collection(Edm.String)" Nullable="false" …
```
> [Feature] Adds support for `RequiresExplicitBinding` and `ExplicitOperationBindings` annotations for operations

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/EdmModelExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/383, https://github.com/microsoft/OpenAPI.NET.OData/issues/382
This PR:
- Updates the operation id generation function for both $count and overloaded function paths.
- Updates the release note.
- Updates integration tests.
> [Fix] Resolves operation ids for `$count` and overloaded functions paths

- README.md
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/OoasUtil/README.md
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/13, https://github.com/microsoft/OpenAPI.NET.OData/issues/253, https://github.com/microsoft/OpenAPI.NET.OData/issues/40
This PR:
- Updates the README for the main library and the `OoasUtil` tool.
- Update the main library README to show in nuget package releases as well.
> Updates README

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiErrorSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1916
This fixes the casing in the default property name for `innerError`. This leads to generation of models with the property as `innererror` causing failing deserialization of the property and therefore the property moved to the additionalData.
Additionally, the [metadata ](https://github.com/microsoftgraph/msgraph-metadata/blob/master/clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsAndErrorsv1.0.xml)defines the property as being camelCased while the generated openApi results in the property name as `innererror`
```xml
<Property Name="innerError" Type="graph.publicInnerError">
<Annotation Term="Org.OData.Core.V1.Description" String="Details of the inner error." />
</Property>
```
> Fixes casing for innerError property in MainError

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/OpenApiExtensions/OpenApiEnumFlagsExtension.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/EdmModelOpenApiExtensionsTest.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/OpenApiExtensions/OpenApiEnumFlagsExtensionTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntitySetPostOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/RefPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/SingletonGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/EntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Closes https://github.com/microsoft/OpenAPI.NET.OData/issues/416 Closes #258
Related to 
Adds the `x-ms-enum-flags` extension to description to enable generation of bitwise enums(https://github.com/microsoft/OpenAPI/pull/8). 
Also fixes XUnit warnings in tests related to using `Assert.Single` for checking collections with only one item.
> Pass Bitwise Enum information

- .vscode/extensions.json
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiErrorSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiExtensions/OpenApiPrimaryErrorMessageExtension.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/OpenApiExtensions/OpenApiPrimaryErrorMessageExtensionTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
related https://github.com/microsoft/kiota/issues/3066
> - adds primary message to error generation

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityOperationalHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/435
This PR:
- Adds schema to content types of stream properties when the property is annotated with an `Org.OData.Core.V1.AcceptableMediaTypes` annotation.
- Updates test to validate this.
- Bumps up the version.
> Adds schema to content types of stream properties that have a collection of acceptable media types

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiLinkGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/437
This PR:
- Generates complex properties of derived types (in addition to navigation properties).
- Introduces a new convert setting `GenerateDerivedTypesProperties` which deprecates the current one `ExpandDerivedTypesNavigationProperties` that will be used to control generation of both complex and navigation properties. 
- Updates integration test files and the relevant unit test.
Dependency: https://github.com/microsoftgraph/msgraph-metadata/issues/465
> [Feature] Retrieves complex properties of derived types

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/442
> [Fix] Updates `operationId`s of navigation property paths with OData type cast segments

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/446
> [Feature] Generates navigation property paths defined in nested complex properties

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPath.cs
- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Common/EdmModelHelper.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Microsoft.OpenAPI.OData.Reader.Tests.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/ComposableFunctions.OData.xml
fixes #402
fixes #404
Generate ODataPath for composable functions
> Support for composable functions

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/410
This PR:
- Appends alternate keys to collection navigation properties
- Updates tests
- Updates release notes
> Adds support for alternate keys to collection navigation properties

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/414
This PR:
- Resolves the issue of all annotated alternate key parameters on an entity being included in the parameters list.
- Updates tests to validate the above fix
> Ensures only alternate key parameter matching key segment identifier is included in path parameters

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityPutOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Common/EdmModelHelper.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityPutOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/399
This PR:
- Enables reading `Org.OData.Capabilities.V1.ReadRestrictions` and `Org.OData.Capabilities.V1.UpdateRestrictions` on structural properties of stream types for media entity paths.
- Updates tests to validate the above.
> [Feature] Reads annotations on structural properties of stream types for media entity paths

- .github/workflows/ci-cd.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntitySetGetOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/423
This PR:
- Updates the format of the request body schema of a collection of complex property
- Updates tests to validate the above
- Updates tests for `Get` complex property description and summary to be retrieved from the `ReadRestriction` annotation.
- Updates release notes
> [Fix] Updates the format of the request body schema of a collection of complex property

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/RefDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/RefPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/RefPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/453
This PR:
- Adds `delete` operation to collection-valued nav. paths with `$ref`. A required query param of `@id` is also included in the list of parameters.
- Updates test and integration files to validate the above.
> [Fix] Adds a `delete` operation and a required `@id` query parameter to collection-valued nav. property paths with `$ref`

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiEdmTypeSchemaGeneratorTest.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiResponseGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/467
This PR:
- Ensures that schemas of properties of collection of complex types are consistent with those of entity types, such that:
```YAML
identities:
type: array
items:
anyOf:
- $ref: '#/components/schemas/microsoft.graph.objectIdentity'
- type: object
nullable: true
```
should be...
```YAML
identities:
type: array
items:
$ref: '#/components/schemas/microsoft.graph.objectIdentity'
```
[NB] Collection of structured types are not nullable.
- Updates tests
- Updates release notes
> [Fix] Fixes inconsistency of nullability of schemas of properties that are a collection of structured types

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/481
This PR:
- Generates `$expand` parameter for operations whose return type is a collection of an entity type.
- Updates tests
- Updates release note.
> Generates `$expand` query parameter for operations whose return type is a collection

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/483
This PR:
- Ensures `delete` operations for non-contained nav. props is generated only if `DeleteRestrictions` exists for this nav. prop and the `Deletable` property is set to `true`.
- Updates test to validate the above.
- Updates release note.
- Minor documentation text fixes to the convert settings.
> Adds `delete` operation for non-contained navigation properties only if explicitly allowed via annotation

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyGetOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/486
This PR:
1. Fixes navigation property paths generated via composable functions by:
- Appending any function parameters to the list of parameters.
- Including the function name in the operation id name. This will help in avoiding duplicates in similar navigation property paths that don't have the composable function. This has been achieved by refactoring the function parameter generation into the central `OpenApiParameterGenerator` class instead of in the `OperationOperationHandler` class.
2. Add a test to validate the above fixes/refactorings.
3. Update the release note
> Appends parameters and fixes operation ids of navigation property paths generated via composable functions

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyGetOperationHandlerTests.cs
This PR:
- Uses alternate key segment identifiers in the generation of operation ids of operations and navigation property alternate paths.
- Adds tests to validate that alternate key identifiers are used in the generation of operation ids.
- Updates the integration test file.
> Use alternate keys in the generation of operation ids of operations and navigation property alternate paths

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/492
This PR:
- Resolves operation id`s of paths with type cast segments that weren't previously included in the operation name.
- Updates the integration tests.
> Fixes operation id`s of paths with type cast segments

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiParameterGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/EdmModelOpenApiExtensionsTest.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiParameterGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/197
This PR:
- Proposes a new convert setting: `UseStringArrayForQueryOptionsSchema` for toggling between generating schemas 
of query options of type string array or enums.
- Uses the above convert setting when generating schemas of query options: `$select`, `$expand` and `$orderby`
- Updates tests to validate the above.
- Updates release notes
> [Fix] Uses convert setting to toggle between generating query options schemas of type string array or enums

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EntitySetPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/InsertRestrictionsType.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/UpdateRestrictionsType.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntitySetPostOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPatchOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPostOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/405
This PR:
- Introduces two new custom annotation properties: `RequestContentTypes` and `ResponseContentTypes` to help provide means of generating expected request body and response content media types for a given endpoint. The current default is `application/json`
- Updates generation of request body and response content media types of entity sets whose entities have media streams to either generate the annotated media type from the annotated `Org.OData.Core.V1.AcceptableMediaTypes` or default to `application/octet-stream` and not generate the `application/json` media type.
- Adds and updates tests to validate the above.
> [Feature] Adds ability to change the response or request body content media type based on custom annotation properties

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/RefDeleteOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/507
> Generates unique DELETE operation ids of `$ref` paths for indexed collection navigation properties

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityOperationalHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/MediaEntityPutOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyDeleteOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandlerProvider.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/MediaEntityPathItemHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/MediaEntityDeleteOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/MediaEntityPathItemHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OData.xml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes #522 
This PR:
- Adds DELETE operations for media content paths unless there are annotations specifying that an entity isn't deletable
- Adds tests to check that the operation details are correct
> Add `delete` operations for media entities

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/OperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/546
> Fixes empty response objects for OData type cast paths

- src/Microsoft.OpenApi.OData.Reader/Edm/ODataPathProvider.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs
- src/Microsoft.OpenApi.OData.Reader/PublicAPI.Unshipped.txt
- test/Microsoft.OpenAPI.OData.Reader.Tests/Edm/ODataPathProviderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/551
Adds the config setting: `ComposableFunctionsExpansionDepth` which provides a control for how many levels composable functions are to be expanded. The default is 1. This means composable functions will be expanded to generate an operation segment or a navigation property segment in the path, but not both. If the value is set to 2, then the latter will be allowed.
> Adds config setting for composable functions generation

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
> Upgrade reader to .NET 8

- src/Microsoft.OpenApi.OData.Reader/Edm/RecordExpressionExtensions.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/PathItem/ComplexPropertyItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/EntityPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/PathItem/NavigationPropertyPathItemHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Vocabulary/Capabilities/UpdateRestrictionsType.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/PathItem/NavigationPropertyPathItemHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/564
> Adds support for retrieving collection of enum values from `UpdateMethod` property of `UpdateRestrictions` annotation

- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiEdmTypeSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiSchemaGenerator.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Basic.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Empty.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/581
> Adds nullable to `double` schema conversions 

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/580
> Creates unique operation ids for paths with composable overloaded functions

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/594
Related to: https://github.com/microsoft/OpenAPI.NET.OData/pull/590
> Ensures unique generation of operation ids for paths with composable overloaded functions where all functions in path are overloaded

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyGetOperationHandlerTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/596
> Fixes potential duplicate operation ids of navigation property paths with overloaded composable functions

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/600
This helps distinguish `PUT` operation ids from `PATCH` operation ids, for paths that potentially supports both.
> Updates `PUT` operation id prefix from `Update` to `Set`

- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/EntityUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyUpdateOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/ComplexPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EntityPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyPutOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
> Updates PUT operation id prefix from Update to Set (#601)

- src/Microsoft.OpenApi.OData.Reader/Common/EdmModelHelper.cs
- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyPostOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ComplexPropertyUpdateOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/DollarCountGetOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/NavigationPropertyOperationHandler.cs
- src/Microsoft.OpenApi.OData.Reader/Operation/ODataTypeCastGetOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/NavigationPropertyGetOperationHandlerTests.cs
Cherry picks changes from #597 onto the v1 branch to resolve checks/generation at https://github.com/microsoftgraph/msgraph-metadata/pull/750
> fix: port #597

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmActionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/Multiple.Schema.OpenApi.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.V2.yaml
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.json
- test/Microsoft.OpenAPI.OData.Reader.Tests/Resources/TripService.OpenApi.yaml
Fixes https://github.com/microsoft/OpenAPI.NET.OData/issues/640
Cherry picks from https://github.com/microsoft/OpenAPI.NET.OData/pull/586 and adds "Actions" or "Functions" as suffixes to the tag. This will
enable the [powershell mappings](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/config/ModulesMapping.jsonc#L42) to be updated to target the paths more precisely to fix the incorrect mappings.
enable the user functions/actions to still remain in their current modules by targeting operationIds like user.*.Actions.
> Adds action/function suffix to tag names for action/function operations

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- src/Microsoft.OpenApi.OData.Reader/Operation/EdmOperationOperationHandler.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Operation/EdmFunctionOperationHandlerTests.cs
Follow up to https://github.com/microsoft/OpenAPI.NET.OData/pull/642
Regression introduced due duplicate operation ids. The change doesn't seem like it was replicated in the v2 branch merge at https://github.com/microsoft/OpenAPI.NET.OData/pull/641. So no need of a second PR.
> Fix duplicate operation ids in overloads that are composable.

- scripts/ValidateProjectVersionUpdated.ps1
> ci: fixes version check script

- src/Microsoft.OpenApi.OData.Reader/Microsoft.OpenAPI.OData.Reader.csproj
- test/Microsoft.OpenAPI.OData.Reader.Tests/Generator/OpenApiSchemaGeneratorTests.cs
- test/Microsoft.OpenAPI.OData.Reader.Tests/Microsoft.OpenAPI.OData.Reader.Tests.csproj
- Fixes a test that was previously failing due to a regression in OAI.NET as a result of NRT support as seen in this comment https://github.com/microsoft/OpenAPI.NET.OData/pull/666/commits/6f52acc33d66dd9c55ed6952e8b4472364ccefb7
- Reference https://github.com/microsoft/OpenAPI.NET/issues/2272
> fix: bump oai version

- src/Microsoft.OpenApi.OData.Reader/Common/Utils.cs
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
> fix: a bug where checking the whether a type is referenced would lead to a null reference exception
